### PR TITLE
Update ignore.txt

### PR DESCRIPTION
**Pull request by vladikoff**
Pls merge or hostile fork! 🍴

### CODE REVIEW

**Comment by miketaylr** [comment]
Seems to be missing "github font"

**Comment by aaronj1335** [comment]
&hellip;he wrote in that awful new github font.

**Comment by miketaylr** [comment]
github please block @aaronj1335 for cyber bulling

**Comment by miketaylr** [comment]
> cyber bulling

🐄 

(bullying too)

**Comment by aaronj1335** [comment]
cyber bulling is probably what millennials are doing these days instead of mechanical bulls

**Pull request merged**
